version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=applicant.settings
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    command: >
      sh -c "until pg_isready -h db -p 5432; do sleep 1; done &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 applicant.wsgi:application"
    networks:
      - applicant_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - media_volume:/app/media
      - app_volume:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A applicant worker --loglevel=info
    networks:
      - applicant_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      args:
        REACT_APP_API_URL: https://applicantcabinet.ru/api/
        REACT_APP_MEDIA_URL: https://applicantcabinet.ru/media/
    volumes:
      - frontend_build:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - applicant_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=applicant_db
      - POSTGRES_USER=applicant_user
      - POSTGRES_PASSWORD=your_secure_db_password
    env_file:
      - .env
    networks:
      - applicant_network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - applicant_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - frontend_build:/usr/share/nginx/html
      - /var/www/applicant/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - frontend
    networks:
      - applicant_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  frontend_build:
  app_volume:

networks:
  applicant_network:
    driver: bridge