# Generated by Django 4.2.11 on 2025-03-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код специальности (например, 09.02.07)', max_length=20, verbose_name='Код специальности')),
                ('name', models.CharField(help_text='Название специальности (например, Информационные системы и программирование)', max_length=200, verbose_name='Название специальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='org.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BuildingSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_places', models.PositiveIntegerField(default=0, verbose_name='Количество бюджетных мест')),
                ('commercial_places', models.PositiveIntegerField(default=0, verbose_name='Количество коммерческих мест')),
                ('commercial_price', models.DecimalField(decimal_places=2, help_text='Цена за обучение на коммерческой основе', max_digits=10, verbose_name='Цена за обучение (коммерция)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_specialties', to='org.building', verbose_name='Корпус')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_specialties', to='org.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность в корпусе',
                'verbose_name_plural': 'Специальности в корпусах',
                'unique_together': {('building', 'specialty')},
            },
        ),
    ]
