# Generated by Django 4.2.11 on 2025-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_specialty_buildingspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Срок обучения'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительные экзамены'),
        ),
    ]
