# Generated by Django 4.2.11 on 2025-03-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_specialty_buildingspecialty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Приоритет заявки (1 - самый высокий)', verbose_name='Приоритет')),
                ('course', models.PositiveIntegerField(default=1, help_text='Курс (по умолчанию 1)', verbose_name='Курс')),
                ('study_form', models.CharField(choices=[('full_time', 'Очно'), ('part_time', 'Заочно')], default='full_time', max_length=20, verbose_name='Форма обучения')),
                ('funding_basis', models.CharField(choices=[('budget', 'Бюджет'), ('commercial', 'Коммерция')], default='budget', max_length=20, verbose_name='Основа обучения')),
                ('dormitory_needed', models.BooleanField(default=False, verbose_name='Нужна ли общага')),
                ('first_time_education', models.BooleanField(default=True, help_text='Среднее/высшее образование впервые', verbose_name='Образование впервые')),
                ('info_source', models.CharField(blank=True, help_text='Источник информации о техникуме', max_length=200, verbose_name='Источник информации')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент')),
                ('building_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='org.buildingspecialty', verbose_name='Специальность в корпусе')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['priority'],
                'unique_together': {('applicant', 'building_specialty')},
            },
        ),
    ]
