# Generated by Django 4.2.11 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
