# Generated by Django 4.2.11 on 2025-05-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_reject_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
