# Generated by Django 4.2.11 on 2025-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_to_data_processing',
            field=models.BooleanField(default=False, verbose_name='Consent to Data Processing'),
        ),
    ]
