# Generated by Django 4.2.11 on 2025-03-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_consent_to_data_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applicant_photos/', verbose_name='Photo')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('citizenship', models.CharField(blank=True, max_length=50, verbose_name='Citizenship')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Place of Birth')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Passport Series')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Passport Number')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Passport Issued Date')),
                ('passport_issued_by', models.CharField(blank=True, max_length=100, verbose_name='Passport Issued By')),
                ('snils', models.CharField(blank=True, max_length=20, verbose_name='SNILS')),
                ('registration_address', models.TextField(blank=True, verbose_name='Registration Address')),
                ('actual_address', models.TextField(blank=True, verbose_name='Actual Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('education_type', models.CharField(blank=True, choices=[('school', 'School'), ('npo', 'NPO'), ('other', 'Other')], max_length=50, verbose_name='Education Type')),
                ('education_institution', models.CharField(blank=True, max_length=100, verbose_name='Education Institution')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('document_type', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], max_length=20, verbose_name='Document Type')),
                ('document_series', models.CharField(blank=True, max_length=10, verbose_name='Document Series')),
                ('document_number', models.CharField(blank=True, max_length=20, verbose_name='Document Number')),
                ('foreign_languages', models.JSONField(blank=True, null=True, verbose_name='Foreign Languages')),
                ('attestation_photo', models.ImageField(blank=True, null=True, upload_to='attestations/', verbose_name='Attestation Photo')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Info')),
                ('mother_full_name', models.CharField(blank=True, max_length=100, verbose_name='Mother Full Name')),
                ('mother_workplace', models.CharField(blank=True, max_length=100, verbose_name='Mother Workplace')),
                ('mother_phone', models.CharField(blank=True, max_length=20, verbose_name='Mother Phone')),
                ('father_full_name', models.CharField(blank=True, max_length=100, verbose_name='Father Full Name')),
                ('father_workplace', models.CharField(blank=True, max_length=100, verbose_name='Father Workplace')),
                ('father_phone', models.CharField(blank=True, max_length=20, verbose_name='Father Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
    ]
