# Generated by Django 4.2.11 on 2025-03-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название или номер корпуса', max_length=100, verbose_name='Название или номер корпуса')),
                ('address', models.CharField(help_text='Полный адрес корпуса', max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Контактный телефон корпуса', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Электронная почта корпуса', max_length=254, verbose_name='Почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
