# Generated by Django 4.2.11 on 2025-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_organization_delete_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consent_to_data_processing',
            field=models.BooleanField(default=True, verbose_name='Consent to Data Processing'),
        ),
    ]
