# Generated by Django 4.2.11 on 2025-04-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_consent_to_data_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average grade (max 5.0)', max_digits=3, null=True, verbose_name='Average Grade'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='calculated_average_grade',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, help_text='Calculated average grade from attestation (read-only)', max_digits=3, null=True, verbose_name='Calculated Average Grade'),
        ),
    ]
