# Generated by Django 4.2.11 on 2025-06-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
