# Generated by Django 4.2.11 on 2025-06-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_applicantprofile_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='task_id',
        ),
    ]
