# Generated by Django 4.2.11 on 2025-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_applicantprofile_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Task ID'),
        ),
    ]
